function xai_input = build_xai_input(eval, scenarioId, iterTag, savePath, prev_state)
% build_xai_input — Build xai_input.json payload for the Python LLM agent
% from a multi-requirement evaluation produced by requirements_eval.
%
%   xai_input = build_xai_input(eval, scenarioId, iterTag)
%   xai_input = build_xai_input(eval, scenarioId, iterTag, "data/xai_input.json")
%   xai_input = build_xai_input(eval, scenarioId, iterTag, savePath, prev_state)
%
% prev_state (optional) is the `_loop_state` struct from the *current*
% scenario. It is forwarded to xai_input.scenario._loop_state so the
% Python adapter's bisection logic can read history.
%
% Schema is backward-compatible with the existing single-requirement layout
% used by xai/main_counterfactual.py and llm_agent/gpt_generator.py, but
% adds a `requirements` array and a `dominant_factors` ranking that mixes
% per-requirement contributions.

if nargin < 3 || isempty(iterTag),    iterTag    = "iter_001"; end
if nargin < 2 || isempty(scenarioId), scenarioId = "scenario_001"; end
if nargin < 4, savePath = ""; end
if nargin < 5, prev_state = []; end

env = eval.scenario_factors;
fog   = env.fog_density_percent;
illum = env.illumination_lux;
noise = env.camera_noise_level;

xai_input = struct();
xai_input.scene_id = char(iterTag);
xai_input.task     = "uav_object_detection_mountain";
xai_input.goal     = "Find minimal environment changes to satisfy all three requirements (REQ-1 mAP50, REQ-2 clearance, REQ-3 continuity).";

% Perception block
xai_input.perception = struct( ...
    "detector",         "geometric+image-feature stub", ...
    "input_resolution", [640, 360], ...
    "detections",       struct([]));

% Scenario block (current values + prev loop state for bisection adapter)
xai_input.scenario = struct( ...
    "scenario_id", char(scenarioId), ...
    "environment_parameters", struct( ...
        "fog_density_percent", fog, ...
        "illumination_lux",    illum, ...
        "camera_noise_level",  noise));
if ~isempty(prev_state)
    xai_input.scenario.x_loop_state = prev_state;
end

% Multi-requirement block
xai_input.requirements = { ...
    struct( ...
        "id",       eval.req1.id, ...
        "name",     eval.req1.name, ...
        "metric",   "map50", ...
        "threshold",eval.req1.threshold, ...
        "value",    eval.req1.value, ...
        "passed",   eval.req1.passed), ...
    struct( ...
        "id",       eval.req2.id, ...
        "name",     eval.req2.name, ...
        "metric",   "min_clearance_m", ...
        "threshold",eval.req2.threshold, ...
        "value",    eval.req2.value, ...
        "passed",   eval.req2.passed), ...
    struct( ...
        "id",       eval.req3.id, ...
        "name",     eval.req3.name, ...
        "metric",   "max_consecutive_misses", ...
        "threshold",eval.req3.threshold, ...
        "value",    eval.req3.value, ...
        "passed",   eval.req3.passed)};

% Backwards-compatible single requirement view (REQ-1)
xai_input.current_requirement = struct( ...
    "metric",               "map50", ...
    "threshold",            eval.req1.threshold, ...
    "value",                eval.req1.value, ...
    "requirement_violated", ~eval.req1.passed);

% Performance signals (overall view)
worstRequirementId = pick_worst_requirement(eval);
failType = "nominal";
if eval.violated_count > 0
    failType = sprintf("violated:%s", worstRequirementId);
end
xai_input.performance_signals = struct( ...
    "map50",                  eval.req1.value, ...
    "min_clearance_m",        eval.req2.value, ...
    "max_consecutive_misses", eval.req3.value, ...
    "violated_count",         eval.violated_count, ...
    "worst_requirement",      worstRequirementId, ...
    "failure_type",           failType);

% XAI signals: dominant factors based on which REQ failed
factors = compute_dominant_factors(eval);
xai_input.xai_signals = struct( ...
    "method", "multi-req-posthoc", ...
    "dominant_factors", factors, ...
    "attention_summary", sprintf( ...
        "REQ-1=%.3f (th=%.2f), REQ-2=%.2fm (th=%.2fm), REQ-3=%d frames (th=%d) at fog=%.1f illum=%.0f noise=%.2f", ...
        eval.req1.value, eval.req1.threshold, ...
        eval.req2.value, eval.req2.threshold, ...
        eval.req3.value, eval.req3.threshold, ...
        fog, illum, noise));

% Constraints + search space (LLM uses these to bound mutations)
xai_input.scenario_constraints = struct( ...
    "allow_weather_change",          true, ...
    "allow_lighting_change",         true, ...
    "allow_obstacle_density_change", false);

xai_input.search_space = struct( ...
    "bounds", struct( ...
        "fog_density_percent", [0.0,   100.0], ...
        "illumination_lux",    [200.0, 20000.0], ...
        "camera_noise_level",  [0.0,   0.6]), ...
    "weights", struct( ...
        "fog_density_percent", 1.0, ...
        "illumination_lux",    1.0, ...
        "camera_noise_level",  1.0), ...
    "mutable_parameters", {{"fog_density_percent","illumination_lux","camera_noise_level"}});

% Counterfactual request (target = make all three pass)
target_status = "PASS";
if eval.all_passed
    target_status = "FAIL";   % search for a harder scenario instead
end
xai_input.counterfactual_request = struct( ...
    "target_status", target_status, ...
    "target_requirements", {{"REQ-1","REQ-2","REQ-3"}}, ...
    "evaluator",     "map50_proxy", ...
    "guidance_blend", struct("xai", 0.5, "shap_global", 0.3, "shap_local", 0.2));

xai_input.sim_result = struct( ...
    "frames",       eval.frames, ...
    "obstacles",    eval.obstacles, ...
    "tp",           eval.req1.tp, ...
    "fp",           eval.req1.fp, ...
    "fn",           eval.req1.fn, ...
    "total_gt",     eval.req1.total_gt, ...
    "min_clearance",eval.req2.value, ...
    "worst_run",    eval.req3.value);

if strlength(savePath) > 0
    txt = jsonencode(xai_input, PrettyPrint=true);
    fid = fopen(savePath, "w");
    if fid < 0, error("Cannot open %s for writing", savePath); end
    fwrite(fid, txt, "char"); fclose(fid);
    fprintf("[XAI] Wrote %s\n", savePath);
end
end

% =========================================================================
% Helpers
% =========================================================================
function id = pick_worst_requirement(eval)
% Return id of the requirement with the largest normalized violation gap.
% A requirement that passes contributes 0; a fail contributes the absolute
% relative gap.
gap = [0 0 0];
if ~eval.req1.passed
    gap(1) = (eval.req1.threshold - eval.req1.value) / max(eps, eval.req1.threshold);
end
if ~eval.req2.passed
    gap(2) = (eval.req2.threshold - eval.req2.value) / max(eps, eval.req2.threshold);
end
if ~eval.req3.passed
    gap(3) = (eval.req3.value - eval.req3.threshold) / max(eps, eval.req3.threshold);
end
[~, idx] = max(gap);
ids = ["REQ-1","REQ-2","REQ-3"];
if all(gap == 0)
    id = "none";
else
    id = char(ids(idx));
end
end

function factors = compute_dominant_factors(eval)
% Heuristic mapping between which REQ failed and which environment factor
% likely drove the failure. Output normalized to sum 1.0.
env = eval.scenario_factors;
fog_n   = max(0, min(1, env.fog_density_percent / 100));
ill_low = max(0, (3000 - env.illumination_lux) / 3000);
ill_hi  = max(0, (env.illumination_lux - 12000) / 12000);
ill_n   = max(ill_low, ill_hi);
noise_n = max(0, min(1, env.camera_noise_level));

w_fog = 0.0; w_ill = 0.0; w_noise = 0.0;

if ~eval.req1.passed
    % REQ-1 driven by perception: weight by current value of each factor
    w_fog   = w_fog   + 0.55 * fog_n;
    w_ill   = w_ill   + 0.30 * ill_n;
    w_noise = w_noise + 0.15 * noise_n;
end
if ~eval.req2.passed
    % REQ-2 mostly geometry; environment plays minor role (visibility into planning)
    w_fog   = w_fog   + 0.25 * fog_n;
    w_ill   = w_ill   + 0.10 * ill_n;
    w_noise = w_noise + 0.05 * noise_n;
end
if ~eval.req3.passed
    % REQ-3 transient: noise + fog dominant
    w_fog   = w_fog   + 0.40 * fog_n;
    w_ill   = w_ill   + 0.15 * ill_n;
    w_noise = w_noise + 0.45 * noise_n;
end

% Fallback if all passed: equal hint
if (w_fog + w_ill + w_noise) <= 0
    w_fog = 0.34; w_ill = 0.33; w_noise = 0.33;
end

s = w_fog + w_ill + w_noise;
w_fog   = w_fog   / s;
w_ill   = w_ill   / s;
w_noise = w_noise / s;

factors = [ ...
    struct("name","fog_density_percent","importance",round(w_fog,3)), ...
    struct("name","illumination_lux",   "importance",round(w_ill,3)), ...
    struct("name","camera_noise_level", "importance",round(w_noise,3))];
end
