"""DSPy optimizer (teleprompter) setup for adversarial UAV scenario generation.

Supports two optimizers:

  'bootstrap' — BootstrapFewShot (default)
      Fast, works well with small datasets (≥ 3 examples).
      Runs the student module on trainset, scores each output with the
      Simulink metric, and keeps the highest-scoring traces as few-shot
      demonstrations for the next call.

  'mipro'     — MIPROv2
      More powerful instruction + demo optimization.
      Requires ~3–5× more LLM calls.  Use when you have ≥ 10 examples
      and want to squeeze out extra adversarial quality.

Public API:
  build_optimizer(metric_fn, optimizer_type='bootstrap', **kwargs)
      → dspy.teleprompt.Teleprompter
"""

from __future__ import annotations

from typing import Callable

import dspy
from dspy.teleprompt import BootstrapFewShot

try:
    from dspy.teleprompt import MIPROv2          # dspy >= 2.4
    _MIPRO_AVAILABLE = True
except ImportError:
    try:
        from dspy.teleprompt import MIPRO as MIPROv2   # older alias
        _MIPRO_AVAILABLE = True
    except ImportError:
        MIPROv2 = None                            # type: ignore[assignment,misc]
        _MIPRO_AVAILABLE = False


def build_optimizer(
    metric_fn: Callable,
    optimizer_type: str = "bootstrap",
    **kwargs,
) -> dspy.teleprompt.Teleprompter:
    """Construct a DSPy teleprompter for adversarial scenario generation.

    Args:
        metric_fn:      simulink_adversarial_metric (or any DSPy-compatible metric).
        optimizer_type: 'bootstrap' or 'mipro'.
        **kwargs:       Forwarded to the chosen optimizer constructor.

    BootstrapFewShot kwargs (defaults shown):
        max_bootstrapped_demos (int=4)  — max demos generated by the teacher
        max_labeled_demos      (int=4)  — max demos taken directly from trainset
        max_rounds             (int=1)  — how many bootstrap rounds to run

    MIPROv2 kwargs (defaults shown):
        auto             (str='medium') — 'light' | 'medium' | 'heavy'
        num_threads      (int=4)        — parallel simulation threads
        max_bootstrapped_demos (int=4)
        max_labeled_demos      (int=4)

    Returns:
        Configured teleprompter ready to call `.compile(module, trainset=…)`.
    """
    if optimizer_type == "bootstrap":
        return BootstrapFewShot(
            metric=metric_fn,
            max_bootstrapped_demos=kwargs.get("max_bootstrapped_demos", 4),
            max_labeled_demos=kwargs.get("max_labeled_demos", 4),
            max_rounds=kwargs.get("max_rounds", 1),
        )

    if optimizer_type == "mipro":
        if not _MIPRO_AVAILABLE:
            print(
                "[Optimizer] Warning: MIPROv2 not found in your DSPy version. "
                "Falling back to BootstrapFewShot.  "
                "Upgrade with: pip install 'dspy>=2.4'"
            )
            return BootstrapFewShot(metric=metric_fn)

        return MIPROv2(
            metric=metric_fn,
            auto=kwargs.get("auto", "medium"),
            num_threads=kwargs.get("num_threads", 4),
            max_bootstrapped_demos=kwargs.get("max_bootstrapped_demos", 4),
            max_labeled_demos=kwargs.get("max_labeled_demos", 4),
        )

    raise ValueError(
        f"Unknown optimizer_type='{optimizer_type}'. "
        "Choose 'bootstrap' (default) or 'mipro'."
    )
